server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: post
          uri: http://localhost:8082
          predicates:
            - Path=/posts/**, 
        - id: comment
          uri: http://localhost:8083
          predicates:
            - Path=/comments/**, 
        - id: dashboard
          uri: http://localhost:8084
          predicates:
            - Path=/dashBoards/**,
        - id: user
          uri: http://localhost:8087
          predicates:
            - Path=/users/**, 
        - id: login
          uri: http://localhost:8087  # 로그인 서비스의 주소로 변경
          predicates:
            - Path=/login,
        - id: logout
          uri: http://localhost:8087  # 로그아웃 서비스의 주소로 변경
          predicates:
            - Path=/logout,    
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: post
          uri: http://post:8080
          predicates:
            - Path=/posts/**, 
        - id: comment
          uri: http://comment:8080
          predicates:
            - Path=/comments/**, 
        - id: dashboard
          uri: http://dashboard:8080
          predicates:
            - Path=/dashBoards/**, 
        - id: user
          uri: http://user:8080
          predicates:
            - Path=/users/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
        - id: login
          uri: http://user:8080  # 로그인 서비스의 주소로 변경
          predicates:
            - Path=/login,
        - id: logout
          uri: http://user:8080  # 로그아웃 서비스의 주소로 변경
          predicates:
            - Path=/logout,    
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080